server:
  port: 8080
  shutdown: immediate
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:popcorn_db}
    username: ${STORE_DB_USERNAME:store_app}
    password: ${STORE_DB_PASSWORD:store123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_enum_jdbc_type: VARCHAR

  cache:
    type: simple

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:popcorn_db}
    user: ${STORE_FLYWAY_USERNAME:store_migrator}
    password: ${STORE_FLYWAY_PASSWORD:store123}
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration/schema
    default-schema: store
    schemas: store
    clean-disabled: false

springdoc:
  server-url: ${GATEWAY_SERVICE_URL:https://dev.goormpopcorn.shop}


jwt:
  secret: ${JWT_SECRET:dGVzdC1qd3Qtc2VjcmV0LWtleS1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQtb25seS1kb25vdC11c2UtaW4tcHJvZHVjdGlvbg==}
  expiration: 3600000
  refresh-expiration-ms: 1209600000

passport:
  secret: ${PASSPORT_SECRET:passport-shared-secret}
  ttl-seconds: 60
