pluginManagement {
    repositories {
        maven { url = uri("https://maven-central.storage-download.googleapis.com/maven2/") }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url = uri("https://maven-central.storage-download.googleapis.com/maven2/") }
        mavenCentral()
    }
}

rootProject.name = 'popcorn-msa'

// 모든 모듈 포함
include 'common-lib'
//include 'backend'  // 일시적으로 제외 - 컴파일 문제로 인해
include 'checkIns'
include 'gateway'
include 'stores'
include 'users'
include 'order'
include 'payment'
include 'orderQuery'
include 'coupon'

// 각 모듈의 위치 지정
project(':common-lib').projectDir = file('common-lib')
project(':checkIns').projectDir = file('checkIns')
project(':gateway').projectDir = file('gateway')
project(':stores').projectDir = file('stores')
project(':users').projectDir = file('users')
project(':order').projectDir = file('order')
project(':payment').projectDir = file('payment')
project(':orderQuery').projectDir = file('orderQuery')
project(':coupon').projectDir = file('coupon')