-- Grant app role access to user_auth schema
GRANT USAGE ON SCHEMA user_auth TO user_auth_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA user_auth TO user_auth_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA user_auth TO user_auth_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA user_auth
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_auth_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA user_auth
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO user_auth_app;
