server:
  port: 8082
  shutdown: immediate
  tomcat:
    uri-encoding: UTF-8
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:popcorn_db}
    username: ${USER_AUTH_DB_USERNAME:user_auth_app}
    password: ${USER_AUTH_DB_PASSWORD:user_auth123}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_auth
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_enum_jdbc_type: NAMED_ENUM

  cache:
    type: simple

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:popcorn_db}
    user:  ${USER_AUTH_FLYWAY_USERNAME:user_auth_migrator}
    password: ${USER_AUTH_FLYWAY_PASSWORD:user321}
    schemas: user_auth
    locations: classpath:db/migration/schema
    baseline-on-migrate: true
    clean-disabled: false
app:
  gateway:
    url: ${GATEWAY_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET:dGVzdC1qd3Qtc2VjcmV0LWtleS1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQtb25seS1kb25vdC11c2UtaW4tcHJvZHVjdGlvbg==}
  expiration: 3600000
  refresh-expiration-ms: 1209600000
passport:
  secret: ${PASSPORT_SECRET:passport-shared-secret}
  ttl-seconds: 60

logging:
  level:
    com.popcorn.demo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
