server:
  port: 8082
  shutdown: immediate
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${USER_AUTH_USERNAME}
    password: ${USER_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_auth
        type:
          preferred_enum_jdbc_type: NAMED_ENUM

  cache:
    type: simple

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user:  ${USER_AUTH_FLYWAY_USERNAME}
    password: ${USER_AUTH_FLYWAY_PASSWORD}
    schemas: user_auth
    locations: classpath:db/migration/schema
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false

springdoc:
  server-url: ${GATEWAY_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration-ms: 1209600000
passport:
  secret: ${PASSPORT_SECRET}
  ttl-seconds: 60

logging:
  level:
    com.popcorn.demo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
app:
  gateway:
    url: ${GATEWAY_SERVICE_URL}
